# Generated by Django 6.0.3 on 2026-03-30 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_imageproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit'),
        ),
    ]
