# Generated by Django 6.0.3 on 2026-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='devise',
            field=models.CharField(choices=[('USD', '$'), ('CDF', 'FC')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
