# Generated by Django 6.0.3 on 2026-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_produit_devise_alter_produit_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('fichier', models.FileField(upload_to='galerie/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
